version: 2
updates:
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "daily"
  - package-ecosystem: "docker"
    directory: "/10-kitten/gnome"
    schedule:
      interval: "daily"
  - package-ecosystem: "docker"
    directory: "/10-kitten/plasma"
    schedule:
      interval: "daily"